---
title: "HBF data pull"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set working directory}
getwd()
setwd("C:/Users/dolee/Desktop")
```

```{r load packages}
library(tidyverse)
install.packages("devtools")
devtools::install_github("ICPI/ICPIutilities")
library(ICPIutilities)
library(readxl)
```

```{r read in your MSD datasets}
df <- read_msd("MER_Structured_Datasets_Site_IM_FY18-20_20200320_v2_2_Nigeria.txt")

df2 <- read_msd("MER_Structured_Datasets_Site_IM_FY18-20_20200320_v2_2_Mozambique.txt")

df3 <- read_excel("sims_analytic_vw_mozambique_nigeria_data_05012020.xlsx")

HFRfiles <- list.files(path="C:/Users/dolee/Desktop", pattern="*.csv", full.names = TRUE) %>%
  lapply(read.csv, stringsAsFactors=F) %>%
  bind_rows()

Rise <- read_msd("C:/Users/dolee/Desktop/MER_Structured_Datasets_Site_IM_FY18-20_20200320_v2_2_Nigeria.txt", save_rds = FALSE)

Rise_df <- read.csv("C:/Users/dolee/Desktop/Rise_20200512_Nigeria.csv")

Zim_OVC <- read_msd("MER_Structured_Datasets_Site_IM_FY18-20_20200605_v1_1_Zimbabwe.txt")
```

```{r Ariana RISE request}
#HTS_TST & HTS_TST_POS, FY18Q1 through FY20Q1
#Niger, Akwa Ibom, Cross River, & Adamawa
Rise %>%
  filter(indicator %in% c("HTS_TST", "HTS_TST_POS")) %>%
  filter(psnu %in% c("Niger", "Akwa Ibom", "Cross River", "Adamawa")) %>%
  filter(standardizeddisaggregate == "Modality/Age/Sex/Result") %>%
  select(-c(snuprioritization, typemilitary, communityprioritization, facilityprioritization, disaggregate, categoryoptioncomboname, ageasentered, trendssemifine, trendscoarse, statustb, statuscx, population, otherdisaggregate, coarsedisaggregate)) %>%
  filter(fundingagency=="USAID") %>%
  split_save(operatingunit, "C:/Users/dolee/Desktop/Data2", "Rise", include_date=TRUE)

#Volume of tests across all testing modalities
#Volume of positive tests from all testing modalities
#Percent yield
#Number needed to test across all testing modalities
#Reshape

Rise_df %>% distinct(standardizeddisaggregate)
Rise_df %>% glimpse()

Rise_df_long <- reshape_msd(Rise_df, "long")
Rise_df_long %>%
  split_save(operatingunit, "C:/Users/dolee/Desktop/Data2", "Rise_df_long", include_date=TRUE)

Rise_df_long %>% distinct(period)
Rise_df_long %>% glimpse()

Rise_df_long %>%
  filter(indicator=="HTS_TST") %>%
  filter(period %in% c("fy2020q1", "fy2019q1", "fy2018q1", "fy2019q2", "fy2018q2", "fy2018q3", "fy2019q3", "fy2019q4", "fy2018q4")) %>%
  group_by(modality, psnu) %>%
  summarise(val=sum(val, na.rm = TRUE)) %>%
  arrange(psnu) %>%
  print(n=Inf)
```

```{r}
HFRfiles %>%
  filter(primepartner %in% c("Family Health International\n", "Chemonics International Inc.\n", "HEARTLAND ALLIANCE LTD-GTE\n")) %>%
  write.csv(., file = "new.csv")
```

```{r Nigeria view}
df %>% 
  glimpse() %>%
  filter(fundingagency == "USAID") %>%
  filter(primepartner %in% c("Heartland Alliance International, LLC", "Family Health International", "Chemonics International, Inc.", "HEARTLAND ALLIANCE LTD-GTE")) %>%
  filter(fiscal_year == 2019 & 2020) %>%
  group_by(fiscal_year) %>%
  summarise() %>%
  print(n=Inf)
```

```{r Nigeria export}
df %>%
  glimpse() %>%
  filter(fundingagency == "USAID") %>%
  filter(primepartner %in% c("Heartland Alliance International, LLC", "Family Health International", "Chemonics International, Inc.", "HEARTLAND ALLIANCE LTD-GTE")) %>%
  filter(fiscal_year == 2019 & fiscal_year == 2020) %>%
  split_save(operatingunit, "C:/Users/dolee/Desktop/Data", "MSD_Site_IM_FY18-20_Data.FI-HBF", include_date=TRUE)
```

```{r Mozambique view}
df2 %>% 
  glimpse() %>%
  filter(fiscal_year == 2019 & fiscal_year == 2020) %>%
  group_by(fiscal_year) %>%
  summarise() %>%
  print()
```

```{r Mozambique export}
df2 %>%
  filter(fundingagency == "USAID") %>%
  filter(mech_code == 70212) %>%
  split_save(operatingunit, "C:/Users/dolee/Desktop/Data2", "MSD_Site_IM_FY19-20_Data.FI-HBF", include_date=TRUE)
```

```{r SIMS view}
df3 %>%
  group_by(ASSESSMENT_QUARTER) %>%
  summarise()
```

```{r SIMS export}
df3 <- df3 %>%
  filter(IMPLEMENTING_MECHANISM_NAME %in% c("14505 - STRENGHTENING INTERGRATED DELIVERY OF HIV/AIDS SERVICES(SIDHAS)", "14505 - AID620A1100002 - STRENGHTENING INTERGRATED DELIVERY OF HIV/AIDS SERVICES(SIDHAS)", "18442 - GHSC-PSM", "14664 - Integrated MARPs HIV Prevention Program (IMHIPP)"))
```

```{r Zim OVC}
Zim_OVC %>%
  filter(fundingagency %in% c("Default"))

?dplyr::group_by

Zim_data <- Zim_OVC %>%
  filter(indicator %in% c("OVC_SERV", "OVC_HIVSTAT")) %>%
  filter(fiscal_year==2020) %>% 
  filter(fundingagency=="USAID") %>%
  select(-c(qtr3, qtr4, modality, snuprioritization, typemilitary, communityprioritization, facilityprioritization))

Zim_data2 <- Zim_OVC %>%
  filter(indicator %in% c("AGYW_PREV")) %>%
  filter(fiscal_year==2020) %>% 
  select(-c(qtr3, qtr4, modality, snuprioritization, typemilitary, communityprioritization, facilityprioritization))
  
Zim_datac <- dplyr::union(Zim_data, Zim_data2)

Zim_datac %>%
  split_save(operatingunit, "C:/Users/dolee/Desktop", "MSD_Site_IM_FY20_DATAFI", include_date=TRUE)

Zim_data %>%
  distinct(indicator, fiscal_year)
```

```{r export csv}
write.csv(df3, "C:/Users/dolee/Desktop/Data/USAID_SIMS_Data.FI-HBF.csv")
```

```{r}
rm(list=ls(all.names=TRUE))
gc()
```

